name: Build m1 grpcio wheel

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build ${{ matrix.os }} ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macOS-11"]
        python_build_version: ["cp38", "cp39", "cp310", "cp311"]
        package: ["grpcio"]

    steps:
      - name: Checkout grpc
        uses: actions/checkout@v3
        with:
          repository: grpc/grpc
          path: grpc
          ref: v1.47.2

      - name: Submodule init
        run: cd grpc && git submodule update --init 

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
#        run: cd grpc && python -m cibuildwheel --output-dir ../wheelhouse
        run:  >
          cd grpc/tools/distrib/python/grpcio_tools && 
          python -m cibuildwheel --output-dir $GITHUB_WORKSPACE/wheelhouse
        env:
          # See https://cibuildwheel.readthedocs.io/en/stable/options/
          # Build the m1 wheel for macs
          CIBW_ARCHS_MACOS: "arm64"
          # Skip all other wheels
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          # Skip tests (wont work on Intel runners)
          CIBW_TEST_SKIP: "*-macosx_arm64"

          # From grpc instructions
          # https://github.com/grpc/grpc/tree/v1.47.2/src/python/grpcio
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
