name: Build

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macOS-11"]
        python_build_version: ["cp38"]
        package: ["grpcio"]

    steps:
      - name: Checkout grpc
        uses: actions/checkout@v3
        with:
          repository: grpc/grpc
          path: grpc
          ref: v1.47.2

      - name: Submodule init
        run: cd grpc && git submodule update --init 

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt; fi"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
